# Generated by Django 4.2.1 on 2023-05-09 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name1', models.CharField(max_length=100, verbose_name='HomePage name1')),
                ('name2', models.CharField(max_length=100, verbose_name='HomePage name2')),
                ('about', models.TextField(verbose_name='HomePage about')),
                ('img', models.ImageField(upload_to='home_images', verbose_name='HomePage image')),
            ],
        ),
    ]
