# Generated by Django 4.2.1 on 2023-05-09 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPageInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img1', models.ImageField(upload_to='about_images', verbose_name='About info image1')),
                ('img2', models.ImageField(upload_to='about_images', verbose_name='About info image2')),
                ('img3', models.ImageField(upload_to='about_images', verbose_name='About info image3')),
                ('img4', models.ImageField(upload_to='about_images', verbose_name='About info image4')),
                ('name1', models.CharField(max_length=100, verbose_name='About info name1')),
                ('name2', models.CharField(max_length=100, verbose_name='About info name2')),
                ('about1', models.TextField(verbose_name='About info about1')),
                ('about2', models.TextField(verbose_name='About info about2')),
                ('num1', models.PositiveIntegerField(verbose_name='About info num1')),
                ('num2', models.PositiveIntegerField(verbose_name='About info num2')),
            ],
        ),
    ]
