# Generated by Django 4.2.1 on 2023-05-09 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_aboutchef'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='menu_images', verbose_name='MenuCategory image')),
                ('name', models.CharField(max_length=60, verbose_name='MenuCategory name')),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='menu_images', verbose_name='Menu image')),
                ('name', models.CharField(max_length=60, verbose_name='Menu name')),
                ('about', models.TextField(verbose_name='Menu about')),
                ('price', models.PositiveIntegerField(verbose_name='Menu price')),
                ('menucategory', models.ManyToManyField(related_name='menu_categ', to='main.menucategory')),
            ],
        ),
    ]
