# Generated by Django 4.2.1 on 2023-05-09 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_menucategory_menu'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Book name')),
                ('email', models.EmailField(max_length=254, verbose_name='Book email')),
                ('data', models.CharField(max_length=30, verbose_name='Book date')),
                ('people_count', models.PositiveIntegerField(verbose_name='People count')),
                ('subject', models.TextField(verbose_name='Subject')),
            ],
        ),
    ]
